apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrplus-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: hrplus-api
  template:
    metadata:
      labels:
        app: hrplus-api
    spec:
      containers:
        - name: hrplus-api
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
