apiVersion: v1
kind: Service
metadata:
  name: hrplus-api
spec:
  selector:
    app: hrplus-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
